name: "yolo-eslint-config"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  registry-url: 'https://registry.npmjs.org/'
                  always-auth: true
            - name: publish
              working-directory: packages
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
              run: npm publish --access public
